project:
  type: website

website:
  title: "Iwasaki Laboratory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: members.qmd
        text: Members
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: access.qmd
        text: Access

format:
  html:
   theme: cosmo
   toc: true
   toc-title: "目次"
   
lang: ja
